[project]
name = 'Decentralized-Public-Service-Digital-Transformation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.accessibility-compliance]
path = 'contracts/accessibility-compliance.clar'
clarity_version = 2
epoch = 2.5

[contracts.agency-verification]
path = 'contracts/agency-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.agency-verification_]
path = 'contracts/agency-verification_.clar'
clarity_version = 2
epoch = 2.5

[contracts.citizen-adoption]
path = 'contracts/citizen-adoption.clar'
clarity_version = 2
epoch = 2.5

[contracts.performance-improvement]
path = 'contracts/performance-improvement.clar'
clarity_version = 2
epoch = 2.5

[contracts.service-digitization]
path = 'contracts/service-digitization.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
